version: '3.9'
services:
  cache:
    image: redis:alpine
    container_name: bliss_cache
    restart: always
    command: redis-server --save 20 1 --loglevel warning --requirepass bliss
    healthcheck:
      test: ['CMD', 'redis-cli', '--raw', 'incr', 'ping']
      interval: 1s
      timeout: 3s
      retries: 10
    ports:
      - 40115:6379
    volumes:
      - ./database/redis:/data

  database:
    image: postgres:alpine
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U prisma']
      interval: 10s
      timeout: 5s
      retries: 5
    container_name: bliss_database
    restart: always
    ports:
      - 40116:5432
    env_file:
      - .env
    volumes:
      - ./database/postgres:/var/lib/postgresql/data

  renzynx:
    container_name: bliss
    working_dir: /app
    restart: always
    image: renzynx/bliss
    ports:
      - 3333:3333
      - 4200:4200
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      database:
        condition: service_healthy
      cache:
        condition: service_healthy
    env_file:
      - .env
volumes:
  cache:
  postgres:
  uploads:
