version: '3.9'
services:
  cache:
    image: redis:alpine
    container_name: bliss_cache
    restart: always
    command: redis-server --save 20 1 --loglevel warning --requirepass bliss
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - ./database/redis:/data
    healthcheck:
      test: ['CMD', 'redis-cli', '--raw', 'incr', 'ping']
      interval: 1s
      timeout: 3s
      retries: 10

  database:
    image: postgres:alpine
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U prisma']
      interval: 10s
      timeout: 5s
      retries: 5
    container_name: bliss_database
    restart: always
    env_file:
      - .env
    ports:
      - ${DATABASE_PORT}:5432
    volumes:
      - ./database/postgres:/var/lib/postgresql/data

  bliss:
    container_name: bliss_app
    working_dir: /app
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3333:3333
      - 4200:4200
    volumes:
      - ./uploads:/app/uploads
      - type: bind
        source: .env
        target: /app/.env
    depends_on:
      database:
        condition: service_healthy
      cache:
        condition: service_healthy
