version: "3.9"
services:
  server:
    image: renzynx/bliss:main
    container_name: bliss
    restart: always
    environment:
      - NODE_ENV=production
      - USE_SSL=true
      - DATABASE_URL=postgresql://postgres:postgrespw@postgres:5432/postgres
      - REDIS_URL=redis://redis:6379
    ports:
      - 69696:3000
    depends_on:
      - postgres
      - redis
    links:
      - postgres
      - redis
    networks:
      - bliss
    volumes:
      - ./uploads:/app/uploads
      - ./thumbnails:/app/thumbnails

  postgres:
    image: postgres:alpine
    container_name: bliss_postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgrespw
    networks:
      - bliss

  redis:
    image: redis:alpine
    container_name: redis
    restart: on-failure
    networks:
      - bliss

networks:
  bliss:
    driver: bridge
