name: Build and push Docker images

on:
  push:
    branches:
      - main
    paths:
      - './api/src/**'
      - './api/prisma/**'
      - './web/src/**'
      - '.github/**'
      - './api/Dockerfile'
      - './web/Dockerfile'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./api
          file: ./api/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/${{ github.actor }}/bliss:latest
          cache-from: type=registry,ref=ghcr.io/${{ github.actor }}/bliss:latest
          cache-to: type=registry,ref=ghcr.io/${{ github.actor }}/bliss:latest,mode=max

  web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./web
          file: ./web/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/${{ github.actor }}/web:latest
          cache-from: type=registry,ref=ghcr.io/${{ github.actor }}/web:latest
          cache-to: type=registry,ref=ghcr.io/${{ github.actor }}/web:latest,mode=max
