name: Docker Image CI

on:
  push:
    branches: ['main']
    paths:
      - 'api/src/**'
      - 'web/src/**'
      - 'api/prisma/**'
      - '.github/**'
      - 'api/Dockerfile'
      - 'web/Dockerfile'
  pull_request:
    branches: ['main']
    paths:
      - 'api/src/**'
      - 'web/src/**'
      - 'api/prisma/**'
      - '.github/**'
      - 'api/Dockerfile'
      - 'web/Dockerfile'

jobs:
  build_api:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    defaults:
      run:
        working-directory: api

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v2
        id: buildx

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image and push to GitHub Container Registry
        uses: docker/build-push-action@v3
        with:
          context: ./api
          file: ./api/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ghcr.io/renzynx/bliss:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  build_web:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    defaults:
      run:
        working-directory: web

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v2
        id: buildx

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image and push to GitHub Container Registry
        uses: docker/build-push-action@v3
        with:
          context: ./web
          file: ./web/Dockerfile
          tags: ghcr.io/renzynx/web:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
